services:
  frigate:
    container_name: frigate
    devices:
      - /dev/dri/renderD128
    env_file: ./.env
    group_add:
      - 105
    restart: always
    image: ghcr.io/blakeblackshear/frigate:stable
    labels:
      traefik.enable: "true"
      traefik.http.services.frigate.loadbalancer.server.port: "5000"
      traefik.http.services.frigate-rtsp.loadbalancer.server.port: "8554"
      traefik.http.routers.frigate.service: 'frigate'
      traefik.http.routers.frigate-rtsp.service: 'frigate-rtsp'
      traefik.http.routers.frigate.entrypoints: "websecure"
      traefik.http.routers.frigate-rtsp.entrypoints: "websecure"
      traefik.http.routers.frigate.rule: "Host(`frigate.x000.dev`) && ! PathPrefix(`/rtsp`)"
      traefik.http.routers.frigate-rtsp.rule: "Host(`calibre.x000.dev`) && PathPrefix(`/rtsp`)"
      traefik.http.routers.frigate-rtsp.middlewares: "default@file, strip-rtsp"
      traefik.http.middlewares.strip-rtsp.stripprefix.prefixes: "/rtsp"
    networks:
      - traefik-proxy
    tmpfs:
      - "/tmp/cache:size=1G"
    volumes:
      - ./config.yaml:/config/config.yml
      - ./storage:/media/frigate

networks:
  traefik-proxy:
    name: traefik-proxy
    external: true
