## For Woox r4785

substitutions:
  device_name: woox0

esphome:
  name: "${device_name}"
  
esp8266:
  board: esp01_1m
  # don't init pins early, else will toggle on reboot or fw update
  early_pin_init: false
  # in case fw reboots (eg if no API access), try to restore state
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: true
  reboot_timeout: 0s
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.10
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret fallback_password

api:
  encryption:
    key: !secret api_key
  on_client_disconnected:
    - logger.log: "API client disconnected! wah wah"
  on_client_connected:
    - logger.log:
        format: "Client %s connected to API with IP %s :)"
        args: ["client_info.c_str()", "client_address.c_str()"]

ota:
  - platform: esphome
    password: !secret ota_password

captive_portal:
logger:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "${device_name} Button"
    id: "${device_name}_button"
    on_click:
      - switch.toggle: "${device_name}_relay"

switch:
  - platform: gpio
    name: "${device_name}"
    id: "${device_name}_relay"
    pin: GPIO05
    # try to restore state, switch off if unable
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: gpio
    pin: GPIO04
    inverted: true
    id: led

sensor:
  - platform: wifi_signal
    name: "WiFi Signal %"
    id: wifi_signal_db
    update_interval: 60s
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    entity_category: "diagnostic"

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "MAC Address"
    scan_results:
      name: "Latest Scan Results"

## Minimal example (in case of OOS error, upload this to flash)
# esphome:
#   name: woox-minimal
#
# esp8266:
#   board: esp01_1m
#
# ota:
#   - platform: esphome
#     password: !secret ota_password
#
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   domain: !secret wifi_password
